import { AnimatedBookOpenTextIcon, AnimatedSearchIcon } from "@/components/AnimatedNavIcons";
import { SavannaShell } from "@/components/SavannaShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BookOpen, CirclePlay, Loader2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";

const LEARN_BANNER_URL = "/learn_banner.png";
type LearnFilter = "all" | "courses" | "lessons" | "paid";

function formatPrice(minor: number, currency: string) { return minor === 0 ? "Free" : new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(minor / 100); }

function CourseCard({ course }: { course: { id: number; slug: string; title: string; description: string | null; category: string | null; priceMinor: number; currencyCode: string } }) {
  return <Link href={`/learn/${course.slug}`} className="savanna-discovery-card group overflow-hidden rounded-[22px] bg-white shadow-[0_8px_20px_rgba(94,58,11,0.04)] transition-transform hover:-translate-y-0.5"><div className="grid h-24 place-items-center bg-[radial-gradient(circle_at_75%_20%,rgba(227,164,60,0.6),transparent_22%),linear-gradient(135deg,#74460d_0%,#d6a552_100%)]"><BookOpen className="size-8 text-white/70" /></div><div className="p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8a765d]">{course.category || "Course"}</p><h3 className="mt-1 text-base font-semibold text-[#4a3824]">{course.title}</h3><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-[#796b56]">{course.description || "A focused Savanna course with modular lessons."}</p><div className="mt-4 flex items-center justify-between gap-3"><span className="text-sm font-semibold text-[#7b4a0d]">{formatPrice(course.priceMinor, course.currencyCode)}</span><span className="inline-flex items-center gap-1 text-sm font-semibold text-[#9a6410]">View <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></div></div></Link>;
}

export default function LearnPage() {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState<LearnFilter>("all");
  const courses = trpc.learning.courses.list.useQuery(query ? { query } : undefined);
  const previewLessons = trpc.learning.courses.previewLessons.useQuery(query ? { query } : undefined);
  const featuredCourses = useMemo(() => (courses.data ?? []).slice(0, 6), [courses.data]);
  const paidCourses = useMemo(() => (courses.data ?? []).filter(course => course.priceMinor > 0), [courses.data]);
  const isLoading = courses.isLoading || previewLessons.isLoading;
  const hasResults = (courses.data?.length ?? 0) > 0 || (previewLessons.data?.length ?? 0) > 0;

  return <SavannaShell><div className="savanna-route-learn space-y-7">
    <section className="savanna-discovery-banner overflow-hidden rounded-[26px]" aria-label="Learning"><img src={LEARN_BANNER_URL} alt="Learning — learn from people you trust" className="block aspect-[8/3] w-full object-cover" /></section>
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><p className="max-w-2xl text-sm leading-6 text-[#796b56]">Structured courses from creators, clear purchase access, and a place to continue at your own pace.</p><Link href="/learn/manage"><Button className="shrink-0 rounded-xl bg-[#5d3a0c] text-white hover:bg-[#412607]"><AnimatedBookOpenTextIcon className="mr-2 size-4" />Teach on Savanna</Button></Link></header>
    <label className="savanna-route-search savanna-desktop-chat-search flex h-12 max-w-xl items-center gap-3 rounded-2xl border border-[#eadfca] bg-white px-4 shadow-[0_6px_14px_rgba(94,58,11,0.035)]"><AnimatedSearchIcon size={17} /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search courses or preview lessons" aria-label="Search courses or preview lessons" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#aa967b]" /></label>
    <div className="savanna-discovery-tabs flex gap-2 overflow-x-auto pb-1" aria-label="Learning discovery filters">{([ ["all", "All"], ["courses", "Courses"], ["lessons", "Lessons"], ["paid", "Paid"] ] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setFilter(value)} aria-pressed={filter === value} data-active={filter === value} className="shrink-0 rounded-full px-3 py-1.5 text-sm font-medium transition-colors">{label}</button>)}</div>
    {isLoading ? <div className="grid min-h-72 place-items-center"><Loader2 className="size-6 animate-spin text-[#9a6410]" /></div> : <>
      {(filter === "all" || filter === "courses") && featuredCourses.length > 0 ? <section className="savanna-discovery-section space-y-4" aria-labelledby="featured-courses-heading"><div className="flex items-end justify-between gap-4"><div><p className="savanna-route-eyebrow text-xs font-semibold uppercase tracking-[0.16em] text-[#9a6410]">Course discovery</p><h2 id="featured-courses-heading" className="mt-1 font-display text-2xl font-semibold tracking-[-0.045em] text-[#3d2d1a]">Featured courses</h2></div><span className="text-xs text-[#796b56]">Newest public courses</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{featuredCourses.map(course => <CourseCard key={course.id} course={course} />)}</div></section> : null}
      {(filter === "all" || filter === "paid") && paidCourses.length > 0 ? <section className="savanna-discovery-section space-y-4" aria-labelledby="paid-courses-heading"><div className="flex items-end justify-between gap-4"><div><p className="savanna-route-eyebrow text-xs font-semibold uppercase tracking-[0.16em] text-[#9a6410]">Paid learning</p><h2 id="paid-courses-heading" className="mt-1 font-display text-2xl font-semibold tracking-[-0.045em] text-[#3d2d1a]">Paid courses</h2></div><span className="text-xs text-[#796b56]">Prices shown upfront</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{paidCourses.map(course => <CourseCard key={course.id} course={course} />)}</div></section> : null}
      {(filter === "all" || filter === "lessons") && previewLessons.data?.length ? <section className="savanna-discovery-section space-y-4" aria-labelledby="preview-lessons-heading"><div className="flex items-end justify-between gap-4"><div><p className="savanna-route-eyebrow text-xs font-semibold uppercase tracking-[0.16em] text-[#9a6410]">Open previews</p><h2 id="preview-lessons-heading" className="mt-1 font-display text-2xl font-semibold tracking-[-0.045em] text-[#3d2d1a]">Preview lessons</h2></div><span className="text-xs text-[#796b56]">Only creator-enabled previews</span></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{previewLessons.data.map(lesson => <Link key={lesson.id} href={`/learn/${lesson.courseSlug}`} className="savanna-discovery-card group rounded-[22px] bg-white p-4 shadow-[0_8px_20px_rgba(94,58,11,0.03)] transition-transform hover:-translate-y-0.5"><span className="grid size-10 place-items-center rounded-xl bg-[#f7e5bd] text-[#9a6410]"><CirclePlay className="size-4" /></span><p className="mt-4 text-xs font-semibold uppercase tracking-[0.12em] text-[#8a765d]">{lesson.courseTitle}</p><h3 className="mt-1 font-semibold text-[#4a3824]">{lesson.title}</h3><p className="mt-2 line-clamp-2 min-h-10 text-sm leading-5 text-[#796b56]">{lesson.summary || "Creator-enabled preview lesson."}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-[#9a6410]">Open course <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" /></span></Link>)}</div></section> : null}
      {!hasResults ? <section className="savanna-discovery-empty grid min-h-80 place-items-center rounded-[30px] bg-[#fffaf0] p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#f7e5bd] text-[#9a6410]"><AnimatedBookOpenTextIcon size={24} /></span><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-0.05em] text-[#3d2d1a]">Good teaching deserves a home.</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#8a765d]">No public courses or creator-enabled preview lessons match this view yet. Creators can publish modular learning and learners control their saved progress choices.</p><Link href="/learn/manage"><Button variant="outline" className="mt-6 rounded-xl border-[#ead2a4] bg-transparent text-[#9a6410]">Create a course</Button></Link></div></section> : null}
    </>}
  </div></SavannaShell>;
}
