import { SavannaShell } from "@/components/SavannaShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CircleAlert, Loader2, ReceiptText } from "lucide-react";
import { Link, useRoute } from "wouter";

function money(minor: number, currency: string) { return new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(minor / 100); }

export default function PaymentDetailPage() {
  const [, params] = useRoute("/payments/:paymentIntentId");
  const paymentIntentId = Number(params?.paymentIntentId);
  const detail = trpc.payments.detail.useQuery({ paymentIntentId }, { enabled: Number.isInteger(paymentIntentId) && paymentIntentId > 0, retry: false });
  if (detail.isLoading) return <SavannaShell><div className="grid min-h-[60vh] place-items-center"><Loader2 className="size-6 animate-spin text-[#31583a]" /></div></SavannaShell>;
  if (!detail.data) return <SavannaShell><section className="grid min-h-[60vh] place-items-center text-center"><div><CircleAlert className="mx-auto size-7 text-[#80572a]" /><h1 className="mt-4 font-display text-3xl font-semibold">Payment request unavailable.</h1><Link href="/payments"><Button variant="outline" className="mt-5 rounded-xl">Back to payments</Button></Link></div></section></SavannaShell>;
  const { intent, receipt } = detail.data;
  return <SavannaShell><div className="mx-auto max-w-[720px] space-y-6"><Link href="/payments" className="inline-flex items-center gap-1 text-sm font-semibold text-[#496348]"><ArrowLeft className="size-4" /> All payments</Link><section className="rounded-[30px] border border-[#dce1d3] bg-white p-7 shadow-[0_14px_35px_rgba(39,54,37,0.04)]"><span className="grid size-12 place-items-center rounded-2xl bg-[#e8dfc9] text-[#80522a]"><ReceiptText className="size-6" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-[#6b8065]">Payment request</p><h1 className="mt-1 font-display text-3xl font-semibold tracking-[-0.05em] text-[#263126]">{intent.paymentReference}</h1><div className="mt-6 grid gap-3 rounded-2xl bg-[#f5f7f3] p-5 sm:grid-cols-2"><div><p className="text-xs text-[#71806d]">Recipient</p><p className="mt-1 font-semibold text-[#354135]">{intent.recipientLabel}</p></div><div><p className="text-xs text-[#71806d]">Payment partner</p><p className="mt-1 font-semibold text-[#354135]">{intent.providerCode}</p></div><div><p className="text-xs text-[#71806d]">Subtotal</p><p className="mt-1 font-semibold text-[#354135]">{money(intent.subtotalMinor, intent.currencyCode)}</p></div><div><p className="text-xs text-[#71806d]">Fee</p><p className="mt-1 font-semibold text-[#354135]">{money(intent.feeMinor, intent.currencyCode)}</p></div><div><p className="text-xs text-[#71806d]">Total</p><p className="mt-1 text-lg font-semibold text-[#24482f]">{money(intent.totalMinor, intent.currencyCode)}</p></div><div><p className="text-xs text-[#71806d]">Status</p><p className="mt-1 font-semibold capitalize text-[#80572c]">{intent.state.replaceAll("_", " ")}</p></div></div>{receipt ? <div className="mt-5 rounded-2xl border border-[#c7dac3] bg-[#f3f8ef] p-5"><p className="text-sm font-semibold text-[#31583a]">Verified receipt</p><p className="mt-2 text-sm text-[#536250]">{receipt.receiptReference} · issued {new Date(receipt.issuedAt).toLocaleString()}</p></div> : <div className="mt-5 rounded-2xl border border-[#e5d3ae] bg-[#fffaf0] p-5 text-sm leading-6 text-[#775b31]">A receipt will appear here only after Savanna receives and verifies the provider callback.</div>}</section></div></SavannaShell>;
}
