import json, pathlib, os

root = pathlib.Path(__file__).resolve().parent.parent
pc = json.loads((root / ".project-config.json").read_text())
secrets = pc.get("secrets", {})
env_vars = pc.get("env_vars", {})

SUPABASE_URL = "https://mfffcdbpuzrmchhatqns.supabase.co"
SUPABASE_PUBLISHABLE_KEY = "sb_publishable_nF-WYyZ6omXeBSvjegO38g_ikLYwvEq"
SUPABASE_JWT_SECRET = "FDZPfTTyFdKsPIiMnsx6afbr4TDm1u1bewsuxpT2STsOa37Mk/ZPEM4T56ZOopsJwrH0OFUZwFL90CIW9Okjiw=="

lines = [
    "# Local development environment. Generated by scripts/write-env.py.",
    "# Gitignored - never commit. Regenerate after rotating any secret.",
    "",
    "NODE_ENV=development",
    "PORT=3000",
    "TRUST_PROXY=1",
    "",
    f"DATABASE_URL={env_vars.get('DATABASE_URL', '')}",
    f"JWT_SECRET={secrets.get('JWT_SECRET', '')}",
    "",
    f"SUPABASE_URL={SUPABASE_URL}",
    f"SUPABASE_PUBLISHABLE_KEY={SUPABASE_PUBLISHABLE_KEY}",
    f'SUPABASE_JWT_SECRET="{SUPABASE_JWT_SECRET}"',
    "",
    "# Exposed to the browser at build time (public by design).",
    f"VITE_SUPABASE_URL={SUPABASE_URL}",
    f"VITE_SUPABASE_PUBLISHABLE_KEY={SUPABASE_PUBLISHABLE_KEY}",
    "",
    f"BUILT_IN_FORGE_API_URL={secrets.get('BUILT_IN_FORGE_API_URL', '')}",
    f'BUILT_IN_FORGE_API_KEY="{secrets.get("BUILT_IN_FORGE_API_KEY", "")}"',
    f"VITE_FRONTEND_FORGE_API_URL={secrets.get('VITE_FRONTEND_FORGE_API_URL', '')}",
    f'VITE_FRONTEND_FORGE_API_KEY="{secrets.get("VITE_FRONTEND_FORGE_API_KEY", "")}"',
    "",
    f"VITE_ANALYTICS_ENDPOINT={secrets.get('VITE_ANALYTICS_ENDPOINT', '')}",
    f"VITE_ANALYTICS_WEBSITE_ID={secrets.get('VITE_ANALYTICS_WEBSITE_ID', '')}",
    "",
    "CSP_ENFORCE=false",
]

target = root / ".env"
target.write_text("\n".join(lines) + "\n")
os.chmod(target, 0o600)

# Never echo the values back - just confirm the shape.
keys = [l.split("=", 1)[0] for l in lines if "=" in l and not l.startswith("#")]
print(f"wrote {target} ({len(keys)} keys, mode 0600)")
empty = [k for k in keys if not dict(
    (l.split("=", 1)[0], l.split("=", 1)[1].strip('"')) for l in lines if "=" in l and not l.startswith("#")
)[k]]
print("empty:", empty if empty else "none")
